### ISSUE TITLE
logLevel error

### ISSUE THREAD

**Issue by ronzim** [pnp/proxy-samples#5]
Running `devproxy -c .\randomerror.devproxyrc.json` I get the following error: 

```
Unhandled exception. System.InvalidOperationException: Failed to convert configuration value at 'LogLevel' to type 'Microsoft.Extensions.Logging.LogLevel'.
 ---> System.FormatException: info is not a valid value for LogLevel.
 ---> System.ArgumentException: Requested value 'info' was not found.
   at System.Enum.TryParseByName[TStorage](RuntimeType enumType, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, TStorage& result)
   at System.Enum.TryParseByValueOrName[TUnderlying,TStorage](RuntimeType enumType, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, TUnderlying& result)
   at System.Enum.TryParse(Type enumType, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, Object& result)
   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   at System.ComponentModel.EnumConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   --- End of inner exception stack trace ---
   at System.ComponentModel.EnumConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.TryConvertValue(Type type, String value, String path, Object& result, Exception& error)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindInstance(Type type, BindingPoint bindingPoint, IConfiguration config, BinderOptions options, Boolean isParentCollection)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindProperty(PropertyInfo property, Object instance, IConfiguration config, BinderOptions options)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindProperties(Object instance, IConfiguration configuration, BinderOptions options)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindInstance(Type type, BindingPoint bindingPoint, IConfiguration config, BinderOptions options, Boolean isParentCollection)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.Bind(IConfiguration configuration, Object instance, Action`1 configureOptions)
   at Microsoft.DevProxy.CommandHandlers.ProxyCommandHandler.<>c.<.cctor>b__12_0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)    
   at System.Lazy`1.CreateValue()
   at Microsoft.DevProxy.CommandHandlers.ProxyCommandHandler.get_Configuration()
   at Program.<>c__DisplayClass0_0.<<Main>$>b__9(ILoggingBuilder builder)
   at Microsoft.Extensions.DependencyInjection.LoggingServiceCollectionExtensions.AddLogging(IServiceCollection services, Action`1 configure)
   at Microsoft.Extensions.Logging.LoggerFactory.Create(Action`1 configure)
   at Program.<>c__DisplayClass0_0.<<Main>$>g__BuildLogger|0()
   at Program.<Main>$(String[] args)
   at Program.<Main>(String[] args)
```

I'm on Win11, using the VSCode terminal.

**Comment by arjunumenon** [comment]
+1  on this error. I am also facing this error. The sample which I am getting this error is this 👉🏾 https://github.com/pnp/proxy-samples/tree/main/samples/demo-randomerror-js

**Comment by waldekmastykarz** [comment]
Thanks for reporting this issue. Sorry I missed it earlier. We've changed log levels at some point which I suspect is causing this issue. We'll get it fixed asap.

**Comment by waldekmastykarz** [comment]
I've just submitted a fix for the sample. In process, I found out another issue which I logged here: https://github.com/microsoft/dev-proxy/issues/949. We'll fix it asap.
